Project Complete
All the main functionalities  of the app are integrated and working as intended, there is only a type error :

occurring at error - src\pages\posts\[slug].tsx (60:23) @ getServerSideProps
TypeError: Cannot read property 'uid' of undefined
  58 |
  59 |     const post = {
> 60 |         slug: response.uid,
     |                       ^

the error is happening in the [slug] component inside, preview folder and [slug] on post folder also showing the same error. I presume its some method that has been updated and require different syntax to fulfill typeScript requirements from Next ServerSide rendering.